import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  ar: {
    // Branding & Global
    brand_name: 'منظومة الإدارة',
    brand_subtitle: 'مركز التحكم المركزي',
    app_title: 'منظومة الإدارة والتحكم',
    app_subtitle: 'لوحة إدارة المنصة الرياضية',
    logout: 'تسجيل الخروج',
    lang_button: 'English',
    cofounder: 'مؤسس شريك',
    admin: 'مشرف نظام',
    player: 'لاعب',
    owner: 'صاحب ملعب',
    currency: 'ج.م',
    all: 'الكل',
    active: 'نشط',
    protected_cofounder_account: 'حساب مؤسس محمي',
    blocked: 'محظور',
    pending: 'معلق',
    confirmed: 'مؤكد',
    completed: 'مكتمل',
    cancelled: 'ملغي',
    save: 'حفظ التعديلات',
    cancel: 'إلغاء',
    delete: 'حذف',
    delete_permanent: 'حذف نهائي',
    confirm: 'تأكيد',
    actions: 'الإجراءات',
    status: 'الحالة',
    name: 'الاسم',
    phone: 'رقم الهاتف',
    email: 'البريد الإلكتروني',
    role: 'الصلاحية',
    governorate: 'المحافظة',
    date: 'التاريخ',
    time: 'الوقت',
    search: 'بحث...',
    refresh_data: 'تحديث البيانات',
    export_data: 'تصدير كشف الحساب',
    no_data: 'لا توجد بيانات متاحة حالياً',
    error_loading: 'حدث خطأ أثناء تحميل البيانات',
    loading: 'جاري التحميل...',
    processing: 'جاري المعالجة...',

    // Sidebar & Navigation
    dashboard: 'لوحة الإحصائيات المركزية',
    owner_audits: 'توثيق واعتماد الملاك',
    owner_subscriptions: 'باقات واشتراكات الملاك',
    users: 'إدارة المستخدمين والمشرفين',
    disputes: 'غرفة فض النزاعات والبلاغات',
    payout_settlements: 'المقاصة والتسويات المالية',
    league_1v1: 'دوري المواجهات الفردية',
    tournaments: 'غرفة تحكم البطولات',
    banners: 'إدارة البنرات والإعلانات',
    settings: 'الرسائل الجماعية والإعدادات',

    // Dashboard Overview
    total_users: 'إجمالي المستخدمين',
    registered_stadiums: 'الملاعب المعتمدة',
    total_bookings: 'حجوزات المباريات',
    total_revenue: 'إجمالي التداولات',
    kpi_users_subtext: 'لاعبين وملاك معتمدين',
    kpi_stadiums_subtext: 'منشأة رياضية نشطة',
    kpi_bookings_subtext: 'مباريات محجوزة ومكتملة',
    kpi_revenue_subtext: 'حجم التداولات عبر المنظومة',
    recent_bookings_title: 'آخر الحجوزات والنشاطات المباشرة',
    booking_id: 'رقم الحجز',
    user_player: 'اللاعب / الحاجز',
    stadium: 'الملعب',
    start_time: 'الموعد المحدد',
    price_deposit: 'السعر / العربون',
    booking_status: 'حالة الحجز',
    edit_booking_title: 'التحكم وتعديل بيانات الحجز',
    edit_booking_btn: 'تحكم وتعديل',
    booking_total_price: 'سعر الحجز الإجمالي (ج.م)',
    booking_deposit_paid: 'العربون المدفوع (ج.م)',
    cancellation_reason_label: 'سبب الإلغاء (يظهر للمستخدم وصاحب الملعب):',
    cancellation_reason_placeholder: 'تم الإلغاء بطلب من الإدارة أو صيانة طارئة...',
    save_booking_success: 'تم تعديل وتحديث بيانات الحجز بنجاح',
    delete_booking_success: 'تم حذف الحجز نهائياً من قاعدة البيانات',
    delete_booking_confirm: 'هل أنت متأكد من حذف هذا الحجز نهائياً؟ هذا الإجراء لا يمكن التراجع عنه.',

    // Owner Audits
    owner_audits_title: 'توثيق واعتماد أصحاب الملاعب',
    owner_audits_subtitle: 'مراجعة وثائق الهوية، السجلات التجارية، وعقود الملاعب قبل تفعيل الحسابات',
    pending_requests_count: 'الطلبات المعلقة',
    action_required: 'يتطلب إجراء',
    no_pending_audits_title: 'لا توجد طلبات توثيق معلقة حالياً',
    no_pending_audits_sub: 'جميع أصحاب الملاعب المسجلين تم اعتماد وثائقهم بنجاح',
    owner_info: 'بيانات المالك',
    stadium_info: 'بيانات الملعب التابع',
    tax_card: 'البطاقة الضريبية',
    commercial_register: 'السجل التجاري',
    national_id_front: 'بطاقة الرقم القومي (الوجه الأمامي)',
    national_id_back: 'بطاقة الرقم القومي (الوجه الخلفي)',
    lease_contract: 'عقد الإيجار / الملكية للملعب',
    approve_owner_btn: 'توثيق واعتماد المالك والملعب',
    tab_ready_audits: 'طلبات جاهزة للمراجعة',
    tab_incomplete_onboarding: 'قيد استكمال التسجيل',
    badge_ready_audit: 'طلب مكتمل للمراجعة',
    badge_draft_lead: 'مسودة / قيد التسجيل',
    no_stadium_yet_title: 'لم يقم المالك بإضافة ملعب بعد',
    no_stadium_yet_desc: 'المستخدم سجل كصاحب ملعب لكنه لم يكمل إضافة بيانات وصور ملعبه عبر تطبيق الموبايل.',
    no_docs_yet_title: 'لا توجد مستندات رسمية مرفوعة',
    no_docs_yet_desc: 'لم يقم المالك برفع أي وثائق ثبوتية (سجل تجاري، بطاقة ضريبية، أو هوية) حتى الآن.',
    cannot_approve_empty_owner: 'لا يمكن الاعتماد لعدم توفر ملعب أو مستندات للتحقق منها',
    whatsapp_contact: 'مراسلة عبر واتساب',
    call_owner: 'اتصال هاتفي',
    incomplete_warning_title: 'حساب قيد التسجيل الأولي (مسودة)',
    incomplete_warning_desc: 'هذا المالك لم يكمل رفع بيانات ملعبه أو مستنداته بعد عبر تطبيق الموبايل. يُنصح بالتواصل معه لمساعدته قبل اتخاذ قرار الرفض.',
    no_incomplete_owners_title: 'لا توجد حسابات متعثرة في التسجيل',
    no_incomplete_owners_sub: 'جميع أصحاب الملاعب قاموا بإضافة ملاعبهم أو رفع وثائقهم بنجاح',
    reject_owner_btn: 'رفض طلب التوثيق',
    reject_modal_title: 'رفض طلب توثيق المالك',
    reject_reason_prompt: 'يرجى ذكر سبب الرفض بوضوح ليظهر للمالك في التطبيق ليقوم بتصحيح البيانات:',
    reject_reason_placeholder: 'مثال: صورة بطاقة الرقم القومي غير واضحة، أو السجل التجاري منتهي...',
    add_owner_manual: 'إضافة مالك وملعب يدوياً',
    add_owner_title: 'إضافة مالك وملعب جديد يدوياً',
    owner_name_label: 'اسم المالك',
    stadium_name_label: 'اسم الملعب',
    price_per_hour_label: 'سعر الساعة (ج.م)',

    // Owner Subscriptions
    owner_subscriptions_title: 'إدارة اشتراكات وباقات الملاك',
    owner_subscriptions_subtitle: 'التحكم في باقات أصحاب الملاعب، تفعيل وتمديد اشتراكات الاحتراف، ومتابعة الفترات التجريبية',
    filter_all_owners: 'الكل',
    filter_pro_owners: 'باقة الاحتراف',
    filter_trial_owners: 'فترة تجريبية (سنة)',
    filter_basic_owners: 'الفترة التجريبية',
    filter_expired_owners: 'منتهي الصلاحية',
    owner_col: 'المالك',
    plan_col: 'نوع الباقة',
    expiry_col: 'تاريخ الانتهاء والمدة',
    capacity_col: 'سعة الملاعب المستخدمة',
    plan_pro: 'باقة الاحتراف',
    plan_trial: 'فترة تجريبية (سنة)',
    plan_basic: 'فترة تجريبية (سنة)',
    plan_expired: 'منتهي الصلاحية',
    trial_ended: 'انتهت التجربة (سنة)',
    permanent: 'فترة تجريبية (سنة)',
    days_left: 'متبقي {days} يوم',
    days_overdue: 'منتهي منذ {days} يوم',
    today_expires: 'ينتهي اليوم',
    unlimited_stadiums: 'غير محدود',
    single_stadium: 'ملعب واحد مسموح',
    stadiums_usage: '{used} من أصل {limit}',
    extend_pro_btn: 'تمديد باقة الاحتراف',
    upgrade_pro_btn: 'ترقية لباقة الاحتراف',
    downgrade_pro_btn: 'إلغاء الترقية (إرجاع للتجريبي)',
    pro_modal_title: 'تفعيل وتمديد باقة الاحتراف',
    duration_days: 'مدة التفعيل (بالأيام):',
    custom_days: 'أو عدد أيام مخصص:',
    cumulative_notice: 'تمديد تراكمي: ستتم إضافة الأيام الجديدة فوق تاريخ الانتهاء الحالي ({date})',
    new_activation_notice: 'تفعيل جديد: سيبدأ سريان الباقة من اليوم ولمدة {days} يوماً',
    pro_features_title: 'مميزات باقة الاحتراف:',
    pro_f1: 'إضافة عدد غير محدود من الملاعب للمنشأة',
    pro_f2: 'تنظيم بطولات وكؤوس خاصة للمنشأة',
    pro_f3: 'ظهور مميز ومقدم في نتائج بحث تطبيق اللاعبين',
    confirm_activate_plan: 'تأكيد حفظ وتفعيل الباقة',
    confirm_downgrade_title: 'إلغاء باقة الاحتراف وإعادة المالك للتجريبي',
    confirm_downgrade_msg: 'هل أنت متأكد من إلغاء باقة الاحتراف للمالك {name}؟ سيعود الحساب إلى الفترة التجريبية وتقتصر سعة الملاعب على ملعب واحد.',
    confirm_downgrade_btn: 'تأكيد إلغاء الترقية',
    subscription_activated_success: 'تم تفعيل باقة الاحتراف للمالك بنجاح',
    subscription_extended_success: 'تم تمديد باقة الاحتراف بنجاح تراكمياً',
    subscription_downgraded_success: 'تم إرجاع المالك للفترة التجريبية بنجاح',

    // Users Moderation
    users_title: 'إدارة المستخدمين والمشرفين',
    users_subtitle: 'البحث عن اللاعبين والملاك، التحكم بالحظر، تصفير غرامات عدم الحضور، واعتماد المشرفين',
    users_management_title: 'إدارة المستخدمين والمشرفين',
    users_management_subtitle: 'البحث عن اللاعبين والملاك، التحكم بالحظر، تصفير غرامات عدم الحضور، واعتماد المشرفين',
    total_users_shown: 'إجمالي المستخدمين المعروضين',
    blocked_accounts: 'الحسابات المحظورة',
    all_roles: 'جميع الأدوار',
    role_players: 'اللاعبين',
    role_owners: 'أصحاب الملاعب',
    role_admins: 'المشرفين',
    role_cofounders: 'المؤسسين الشركاء',
    all_statuses: 'جميع الحالات',
    status_active_only: 'نشط فقط',
    status_blocked_only: 'محظور فقط',
    user_col: 'المستخدم',
    account_status_col: 'حالة الحساب',
    no_show_col: 'حالات عدم الحضور',
    block_user: 'حظر المستخدم',
    unblock_user: 'فك الحظر',
    reset_noshow_btn: 'تصفير عداد عدم الحضور',
    approve_admin_btn: 'اعتماد حساب المشرف',
    confirm_delete_user: 'تأكيد حذف المستخدم نهائياً',
    delete_user_modal_title: 'تأكيد حذف المستخدم نهائياً',
    delete_user_prompt: 'هل أنت متأكد من رغبتك في حذف حساب هذا المستخدم نهائياً من النظام؟',
    yes_delete_permanently: 'نعم، حذف نهائي',
    uploaded_documents: 'وثائق مرفوعة',
    view: 'معاينة',
    wipe_season_prompt: 'سيقوم هذا الإجراء بمسح كافة طلبات التسجيل السابقة وتفريغ البوابة لبدء دورة تسجيل جديدة للموسم القادم. هل أنت متأكد؟',
    save_changes: 'حفظ التعديلات',
    noshow_reset_success: 'تم تصفير عداد عدم الحضور للاعب بنجاح',
    admin_approved_success: 'تم اعتماد وتفعيل صلاحيات المشرف بنجاح',
    user_deleted_success: 'تم حذف حساب المستخدم نهائياً بنجاح',
    dispute_resolved_success: 'تم اعتماد قرار فض النزاع وتحديث المباراة بنجاح',
    protected_account: 'حساب محمي سيادياً',
    cannot_block_self_or_cofounder: 'لا يمكن حظر هذا الحساب (حساب محمي للمؤسسين الشركاء أو حسابك الحالي)',
    dispute_escrow_refund_notice: 'تنبيه مالي: اعتماد قرار الإلغاء سيقوم بإلغاء الحجز وتوجيه رد العربون للاعب وإسقاط مستحقات المالك.',

    // Disputes
    disputes_title: 'غرفة فض النزاعات وبلاغات المباريات',
    disputes_subtitle: 'الفصل في نتائج المباريات المتنازع عليها، مراجعة أدلة الفرق، واعتماد النتائج النهائية',
    no_disputes_title: 'لا توجد نزاعات مفتوحة حالياً',
    no_disputes_sub: 'كافة المباريات تسير بشكل منتظم والنتائج معتمدة',
    home_team: 'الفريق المضيف',
    away_team: 'الفريق الضيف',
    dispute_reason: 'سبب النزاع والملاحظات',
    resolve_btn: 'الفصل واعتماد النتيجة',
    resolve_modal_title: 'الفصل في نتيجة النزاع',
    final_decision_label: 'القرار النهائي:',
    home_win_opt: 'فوز الفريق المضيف',
    away_win_opt: 'فوز الفريق الضيف',
    draw_opt: 'اعتماد تعادل',
    cancelled_opt: 'إلغاء واسترداد',

    // Payout Settlements
    payout_title: 'المقاصة والتسويات المالية للملاك',
    payout_subtitle: 'إدارة مستحقات أصحاب الملاعب، متابعة المبالغ المحصلة في حسابك، وتأكيد تحويلات الكاش وإنستاباي',
    tab_owner_matrix: 'كشف حساب وأرصدة الملاك',
    tab_ledger: 'سجل المعاملات والعمليات',
    tab_requests: 'طلبات السحب الواردة',
    kpi_gross_volume: 'إجمالي تداولات الملاعب',
    kpi_gross_subtext: 'إجمالي مبالغ الحجوزات المسجلة',
    kpi_online_collected: 'المحصل في حساب المنصة',
    kpi_online_subtext: 'عربونات ودفع إلكتروني داخل حسابك',
    kpi_platform_commission: 'أرباح وعمولات المنصة الصافية',
    kpi_platform_subtext: 'العمولات المستحقة للمنصة من الحجوزات',
    kpi_pending_dues: 'مستحقات جاهزة للصرف (مكتملة)',
    kpi_pending_subtext: 'صافي أرباح المباريات المكتملة المنتهية',
    kpi_escrow_held: 'أمانات معلقة (مباريات قادمة)',
    kpi_escrow_subtext: 'مبالغ محتجزة كأمانة حتى موعد اللعب',
    upcoming_escrow_note: 'معلقة لمباراة قادمة',
    kpi_total_settled: 'إجمالي ما تم تحويله وتسويته',
    kpi_settled_subtext: 'مبالغ تم تحويلها بنجاح لأصحاب الملاعب',
    owner_statement_col: 'اسم المالك',
    gross_volume_col: 'إجمالي الحجوزات',
    online_collected_col: 'المحصل في حسابنا',
    platform_fee_col: 'عمولة المنصة',
    settled_payouts_col: 'المصروف سابقاً',
    net_withdrawable_col: 'صافي المستحق للمالك',
    ready_for_payout: 'مستحق للصرف',
    no_dues: 'تمت التسوية',
    negative_due: 'مستحق على المالك',
    no_destination_registered: 'لم يسجل وسيلة تحويل بعد',
    settle_now_btn: 'تسوية وصرف الرصيد',
    payout_modal_title: 'صرف وتسوية مستحقات المالك',
    amount_to_transfer: 'المبلغ المراد تحويله (ج.م) *',
    transfer_method: 'طريقة التحويل *',
    vodafone_cash: 'فودافون كاش',
    instapay: 'إنستاباي',
    bank_transfer: 'تحويل بنكي',
    cash_direct: 'تسليم نقدي مباشر',
    wallet_number_account: 'رقم المحفظة / الحساب *',
    reference_number: 'رقم الإيصال / المرجع *',
    confirm_payout_btn: 'تأكيد تسجيل الصرف وتحديث الرصيد',
    settlement_success: 'تم تسجيل التحويل وتسوية مستحقات المالك بنجاح',

    // 1v1 League
    league_title: 'دوري المواجهات الفردية',
    league_subtitle: 'إدارة تصنيفات اللاعبين، اعتماد المتقدمين، التحكم ببوابة التسجيل، وتحديث الإحصائيات',
    gate_open_label: 'بوابة التسجيل مفتوحة',
    gate_closed_label: 'بوابة التسجيل مغلقة',
    add_player_manual: 'إضافة لاعب يدوياً',
    wipe_season_title: 'بدء موسم جديد',
    tab_standings: 'جدول الترتيب وتصنيف الأبطال',
    tab_registrations: 'طلبات الانضمام المعلقة',
    rank_col: 'الترتيب',
    player_col: 'اللاعب',
    total_points_col: 'مجموع النقاط',
    skill_points_col: 'نقاط المهارة',
    goals_col: 'الأهداف',
    titles_col: 'الألقاب',
    trend_col: 'المستوى / الترند',
    trend_up: 'تصاعدي',
    trend_stable: 'مستقر',
    trend_down: 'تراجع',
    add_player_modal_title: 'إضافة لاعب جديد لدوري المواجهات الفردية',
    initial_points: 'النقاط الافتتاحية',
    edit_player_modal_title: 'تعديل بيانات وإحصائيات اللاعب',

    // Tournament Control
    tournaments_title: 'غرفة تحكم البطولات والكؤوس',
    tournaments_subtitle: 'إدارة البطولات العامة وبطولات الملاك، وتوليد شجرة المباريات وتحديد المراحل',
    no_tournaments_title: 'لا توجد بطولات حالياً',
    tournament_name_col: 'اسم البطولة',
    teams_count_col: 'عدد الفرق',
    generate_bracket_btn: 'توليد شجرة المباريات',
    stage_col: 'المرحلة الحالية',

    // CRM Settings
    crm_title: 'مركز البث الجماعي وإعدادات المنظومة',
    crm_subtitle: 'إرسال الإشعارات الجماعية الموجهة للاعبين والملاك، والتحكم بوضع صيانة التطبيق',
    broadcast_card_title: 'إرسال إشعار جماعي فوري',
    target_audience_label: 'الفئة المستهدفة:',
    audience_all: 'كافة المستخدمين (لاعبين وملاك)',
    audience_players: 'اللاعبين فقط',
    audience_owners: 'أصحاب الملاعب فقط',
    notif_title_label: 'عنوان الإشعار',
    notif_body_label: 'نص الإشعار والتفاصيل',
    notif_title_placeholder: 'مثال: تحديث مواعيد دوري المواجهات الفردية',
    notif_body_placeholder: 'اكتب تفاصيل الرسالة بوضوح...',
    send_notif_btn: 'إرسال الإشعار الآن',
    maintenance_title: 'وضع الصيانة للتطبيقات',
    maintenance_desc: 'قفل التطبيق المؤقت أثناء التحديثات الكبرى. عند التفعيل سيتم إيقاف الحجوزات وتوجيه المستخدمين لشاشة الصيانة.',
    maintenance_active_status: 'وضع الصيانة نشط',
    maintenance_inactive_status: 'الخدمة تعمل طبيعياً',
    enable_maintenance: 'تفعيل الصيانة',
    disable_maintenance: 'إيقاف الصيانة',

    // Missing keys discovered in deep audit
    live_stream: 'مباشر',
    maintenance_toggle: 'التحكم بوضع الصيانة',
    pending_approval: 'في انتظار الموافقة',
    pending_note: 'تم استلام طلبك، سيتم مراجعته من قبل المؤسس الشريك والرد عليك في أقرب وقت.',
    infra_health_title: 'مؤشرات البنية التحتية',
    infra_db: 'قاعدة البيانات',
    infra_db_status: 'متصل',
    infra_region: 'منطقة الخادم',
    infra_rpc: 'دوال المعاملات',
    infra_rpc_status: 'مفعّلة',
    toast_owner_approved: 'تم توثيق المالك واعتماد الملعب بنجاح',
    toast_owner_rejected: 'تم رفض طلب التوثيق',
    toast_owner_added: 'تمت إضافة المالك والملعب وتفعيلهما بنجاح',
    toast_fill_required: 'يرجى ملء جميع الحقول الإلزامية',
    toast_fail_generic: 'فشلت العملية، يرجى المحاولة لاحقاً',
    toast_gate_opened: 'تم فتح بوابة تسجيل دوري المواجهات الفردية بنجاح',
    toast_gate_closed: 'تم إغلاق بوابة التسجيل والاكتفاء بالعدد الحالي',
    toast_season_wiped: 'تم تصفير وبدء الموسم الجديد بنجاح',
    toast_player_approved: 'تم اعتماد اللاعب وإضافته لجدول الترتيب بنجاح',
    toast_player_rejected: 'تم رفض طلب الانضمام',
    toast_player_added: 'تم إضافة اللاعب إلى قائمة الدوري بنجاح',
    toast_stats_saved: 'تم تحديث إحصائيات ونقاط اللاعب بنجاح',
    toast_bracket_generated: 'تم توليد شجرة مباريات البطولة بنجاح',
    toast_status_updated: 'تم تحديث حالة البطولة بنجاح',
    toast_maintenance_on: 'تم تفعيل وضع الصيانة بنجاح',
    toast_maintenance_off: 'تم إلغاء وضع الصيانة وعودة المنصة للعمل الطبيعي',
    toast_broadcast_sent: 'تم إرسال الإشعار الجماعي بنجاح',
    toast_broadcast_fill: 'يرجى كتابة عنوان ونص الإشعار',
    try_different_filters: 'جرّب تغيير معايير البحث أو الفلاتر',
    preview_doc: 'معاينة المستند',
    open_in_new_tab: 'فتح بنافذة جديدة',

    // Login & Auth
    login_title: 'تسجيل الدخول للنظام',
    login_sub: 'أدخل البريد الإلكتروني وكلمة المرور للوصول للوحة الإدارة',
    email_label: 'البريد الإلكتروني',
    password_label: 'كلمة المرور',
    full_name_label: 'الاسم بالكامل',
    phone_label: 'رقم الهاتف',
    btn_login: 'تسجيل الدخول',
    btn_register: 'طلب إنشاء حساب أدمن جديد',
    already_have_account: 'لديك حساب بالفعل؟ تسجيل الدخول',
    send_admin_request: 'إرسال طلب تفعيل المشرف',

    // Banners & Ads Management
    banners_title: 'إدارة البنرات والإعلانات التفاعلية',
    banners_subtitle: 'التحكم في إعلانات التطبيق، رفع الصور، تحديد مدة العرض، ومتابعة المشاهدات والنقرات',
    add_new_banner: 'إضافة بنر إعلاني جديد',
    edit_banner: 'تعديل بيانات البنر',
    total_banners: 'إجمالي البنرات',
    active_banners: 'البنرات النشطة حالياً',
    total_banner_views: 'إجمالي المشاهدات',
    total_banner_clicks: 'إجمالي النقرات',
    ctr_rate: 'معدل التفاعل (CTR)',
    banner_title: 'عنوان البنر / الحملة',
    banner_title_placeholder: 'مثال: عرض الصيف على ملاعب التجمع...',
    banner_desc: 'وصف إضافي (اختياري)',
    banner_desc_placeholder: 'تفاصيل إضافية عن العرض أو الإعلان...',
    banner_image: 'صورة البنر الإعلاني',
    upload_image_note: 'اسحب وأفلت الصورة هنا أو اضغط للاختيار (PNG, JPG, WebP بحد أقصى 5MB)',
    target_url: 'رابط التوجيه (اختياري)',
    target_url_placeholder: 'https://example.com/promo أو مسار داخل التطبيق',
    placement: 'مكان ظهور البنر',
    placement_all: 'كافة المواضع',
    placement_home_slider: 'سلايدر الشاشة الرئيسية (Home Slider)',
    placement_popup: 'نافذة منبثقة (Pop-up Modal)',
    placement_tournaments: 'شاشة البطولات (Tournaments Screen)',
    duration_seconds: 'مدة العرض للشريحة (بالثواني)',
    duration_seconds_hint: 'المدة التي يستغرقها البنر قبل الانتقال للشريحة التالية (الافتراضي: 5 ثواني)',
    start_date: 'تاريخ بداية العرض',
    end_date: 'تاريخ انتهاء العرض (اختياري)',
    priority_order: 'ترتيب الأولوية',
    priority_order_hint: 'الأرقام الأقل تظهر أولاً (مثلاً: 1 يظهر قبل 2)',
    banner_status: 'حالة البنر',
    status_active: 'نشط ويعمل',
    status_disabled: 'معطل',
    status_expired: 'منتهي الصلاحية',
    status_scheduled: 'مجدول مستقبلاً',
    confirm_delete_banner: 'هل أنت متأكد من حذف هذا البنر الإعلاني نهائياً؟ هذا الإجراء لا يمكن التراجع عنه.',
    banner_saved_success: 'تم حفظ بيانات البنر بنجاح',
    banner_deleted_success: 'تم حذف البنر بنجاح',
    banner_status_updated: 'تم تحديث حالة البنر بنجاح',
    no_banners_found: 'لا توجد بنرات إعلانية مضافة حتى الآن',
    no_banners_sub: 'اضغط على زر "إضافة بنر إعلاني جديد" لإنشاء أول حملة إعلانية في التطبيق',
    change_image: 'تغيير الصورة',
    select_image_required: 'يرجى اختيار صورة للبنر أولاً',
    uploading_image: 'جاري رفع الصورة إلى التخزين السحابي...',
    banner_active_now: 'نشط حالياً',
    banner_inactive: 'غير مفعّل',
    filter_by_status: 'الحالة',
    filter_by_placement: 'موضع العرض',
  },
  en: {
    // Branding & Global
    brand_name: 'Management Panel',
    brand_subtitle: 'Central Control Hub',
    app_title: 'Master Control Panel',
    app_subtitle: 'Sports Platform Management System',
    logout: 'Sign Out',
    lang_button: 'العربية',
    cofounder: 'Co-Founder',
    admin: 'Administrator',
    player: 'Player',
    owner: 'Stadium Owner',
    currency: 'EGP',
    all: 'All',
    active: 'Active',
    protected_cofounder_account: 'Protected Co-Founder',
    blocked: 'Blocked',
    pending: 'Pending',
    confirmed: 'Confirmed',
    completed: 'Completed',
    cancelled: 'Cancelled',
    save: 'Save Changes',
    cancel: 'Cancel',
    delete: 'Delete',
    delete_permanent: 'Delete Permanently',
    confirm: 'Confirm',
    actions: 'Actions',
    status: 'Status',
    name: 'Name',
    phone: 'Phone Number',
    email: 'Email Address',
    role: 'Role',
    governorate: 'Governorate',
    date: 'Date',
    time: 'Time',
    search: 'Search...',
    refresh_data: 'Refresh Data',
    export_data: 'Export Statement',
    no_data: 'No data available',
    error_loading: 'Error loading data',
    loading: 'Loading...',
    processing: 'Processing...',

    // Sidebar & Navigation
    dashboard: 'Central Analytics Dashboard',
    owner_audits: 'Owner Audits & Verification',
    owner_subscriptions: 'Owner Pro Subscriptions',
    users: 'User & Admin Moderation',
    disputes: 'Dispute Resolution Center',
    payout_settlements: 'Financial Clearing & Payouts',
    league_1v1: '1v1 Match League',
    tournaments: 'Tournament Command Center',
    banners: 'Banners & Ads Management',
    settings: 'Broadcast & System Settings',

    // Dashboard Overview
    total_users: 'Total Users',
    registered_stadiums: 'Approved Stadiums',
    total_bookings: 'Match Bookings',
    total_revenue: 'Total Turnover',
    kpi_users_subtext: 'Verified players and owners',
    kpi_stadiums_subtext: 'Active sports venues',
    kpi_bookings_subtext: 'Confirmed and completed matches',
    kpi_revenue_subtext: 'Total transaction volume',
    recent_bookings_title: 'Latest Live Bookings & Activities',
    booking_id: 'Booking ID',
    user_player: 'Player / Booker',
    stadium: 'Stadium',
    start_time: 'Scheduled Time',
    price_deposit: 'Price / Deposit',
    booking_status: 'Booking Status',
    edit_booking_title: 'Manage & Edit Booking',
    edit_booking_btn: 'Manage & Edit',
    booking_total_price: 'Total Price (EGP)',
    booking_deposit_paid: 'Deposit Paid (EGP)',
    cancellation_reason_label: 'Cancellation Reason (visible to user & owner):',
    cancellation_reason_placeholder: 'Cancelled due to urgent maintenance or management request...',
    save_booking_success: 'Booking details updated successfully',
    delete_booking_success: 'Booking permanently deleted',
    delete_booking_confirm: 'Are you sure you want to permanently delete this booking? This action cannot be undone.',

    // Owner Audits
    owner_audits_title: 'Owner Verification & Audits',
    owner_audits_subtitle: 'Review identity documents, commercial registries, and venue contracts before account activation',
    pending_requests_count: 'Pending Requests',
    action_required: 'Action Required',
    no_pending_audits_title: 'No Pending Audits',
    no_pending_audits_sub: 'All registered stadium owners have verified documents',
    owner_info: 'Owner Information',
    stadium_info: 'Associated Stadium Information',
    tax_card: 'Tax Card',
    commercial_register: 'Commercial Registry',
    national_id_front: 'National ID (Front)',
    national_id_back: 'National ID (Back)',
    lease_contract: 'Lease / Ownership Contract',
    approve_owner_btn: 'Approve Owner & Stadium',
    tab_ready_audits: 'Ready for Review',
    tab_incomplete_onboarding: 'Incomplete Onboarding',
    badge_ready_audit: 'Ready for Review',
    badge_draft_lead: 'Draft / In Progress',
    no_stadium_yet_title: 'No Stadium Registered Yet',
    no_stadium_yet_desc: 'The user registered as an owner but has not yet completed the stadium creation wizard in the mobile app.',
    no_docs_yet_title: 'No Verification Documents Uploaded',
    no_docs_yet_desc: 'The owner has not uploaded any official documents (commercial registry, tax card, or ID) yet.',
    cannot_approve_empty_owner: 'Cannot approve: No stadium or documents available to verify',
    whatsapp_contact: 'Contact via WhatsApp',
    call_owner: 'Call Owner',
    incomplete_warning_title: 'Account in Early Onboarding (Draft)',
    incomplete_warning_desc: 'This owner has not finished submitting venue details or documents. Consider contacting them to assist before taking rejection action.',
    no_incomplete_owners_title: 'No Incomplete Owner Accounts',
    no_incomplete_owners_sub: 'All registered owners have added venues or uploaded documents',
    reject_owner_btn: 'Reject Audit Request',
    reject_modal_title: 'Reject Owner Audit Request',
    reject_reason_prompt: 'Specify the rejection reason clearly so the owner can correct their submitted documents:',
    reject_reason_placeholder: 'Example: National ID photo is blurry, or Commercial Registry is expired...',
    add_owner_manual: 'Add Owner & Stadium Manually',
    add_owner_title: 'Manually Add Owner & Venue',
    owner_name_label: 'Owner Name',
    stadium_name_label: 'Stadium Name',
    price_per_hour_label: 'Price Per Hour (EGP)',

    // Owner Subscriptions
    owner_subscriptions_title: 'Owner Subscriptions Management',
    owner_subscriptions_subtitle: 'Manage owner subscription tiers, activate & extend Pro plans, and monitor free trials',
    filter_all_owners: 'All',
    filter_pro_owners: 'Pro Plan',
    filter_trial_owners: 'Free Trial (1 Year)',
    filter_basic_owners: 'Free Trial',
    filter_expired_owners: 'Expired',
    owner_col: 'Owner',
    plan_col: 'Subscription Plan',
    expiry_col: 'Expiry Date & Duration',
    capacity_col: 'Stadium Capacity & Usage',
    plan_pro: 'Pro Plan',
    plan_trial: 'Free Trial (1 Year)',
    plan_basic: 'Free Trial (1 Year)',
    plan_expired: 'Expired',
    trial_ended: 'Trial Ended (1 Year)',
    permanent: 'Free Trial (1 Year)',
    days_left: '{days} days left',
    days_overdue: 'expired {days} days ago',
    today_expires: 'Expires today',
    unlimited_stadiums: 'Unlimited',
    single_stadium: '1 stadium allowed',
    stadiums_usage: '{used} of {limit}',
    extend_pro_btn: 'Extend Pro Plan',
    upgrade_pro_btn: 'Upgrade to Pro Plan',
    downgrade_pro_btn: 'Revoke Pro (Return to Trial)',
    pro_modal_title: 'Activate & Extend Pro Plan',
    duration_days: 'Activation Duration (Days):',
    custom_days: 'Or custom days duration:',
    cumulative_notice: 'Cumulative extension: new days will be added to the current expiry date ({date})',
    new_activation_notice: 'New activation: plan will start from today for {days} days',
    pro_features_title: 'Pro Plan Features:',
    pro_f1: 'Add unlimited stadiums under one organization',
    pro_f2: 'Host and organize private cups and tournaments for the venue',
    pro_f3: 'Featured listing in player search results',
    confirm_activate_plan: 'Save & Confirm Plan Activation',
    confirm_downgrade_title: 'Revoke Pro & Return to Trial',
    confirm_downgrade_msg: 'Are you sure you want to revoke Pro plan for {name}? The account will return to the free trial tier with 1 stadium capacity limit.',
    confirm_downgrade_btn: 'Confirm Revocation',
    subscription_activated_success: 'Pro plan activated successfully',
    subscription_extended_success: 'Pro plan extended cumulatively successfully',
    subscription_downgraded_success: 'Owner returned to free trial tier successfully',

    // Users Moderation
    users_title: 'User & Admin Moderation',
    users_subtitle: 'Search players and owners, manage bans, reset no-show counts, and authorize administrators',
    users_management_title: 'User & Admin Moderation',
    users_management_subtitle: 'Search players and owners, manage bans, reset no-show counts, and authorize administrators',
    total_users_shown: 'Total Users Displayed',
    blocked_accounts: 'Blocked Accounts',
    all_roles: 'All Roles',
    role_players: 'Players',
    role_owners: 'Stadium Owners',
    role_admins: 'Administrators',
    role_cofounders: 'Co-Founders',
    all_statuses: 'All Statuses',
    status_active_only: 'Active Only',
    status_blocked_only: 'Blocked Only',
    user_col: 'User',
    account_status_col: 'Account Status',
    no_show_col: 'No-Show Violations',
    block_user: 'Block User',
    unblock_user: 'Unblock User',
    reset_noshow_btn: 'Reset No-Show Count',
    approve_admin_btn: 'Authorize Admin Account',
    confirm_delete_user: 'Confirm Permanent User Deletion',
    delete_user_modal_title: 'Permanently Delete User',
    delete_user_prompt: 'Are you sure you want to permanently delete user account',
    yes_delete_permanently: 'Yes, Delete Permanently',
    uploaded_documents: 'Uploaded Documents',
    view: 'Preview',
    wipe_season_prompt: 'This action will clear all previous registrations and open the gate for a new season cycle. Are you sure?',
    save_changes: 'Save Changes',
    noshow_reset_success: 'Player no-show count reset successfully',
    admin_approved_success: 'Admin account approved and authorized successfully',
    user_deleted_success: 'User account permanently deleted successfully',
    dispute_resolved_success: 'Dispute decision finalized and saved successfully',
    protected_account: 'Protected Account',
    cannot_block_self_or_cofounder: 'Cannot block this protected account (co-founder or your current session)',
    dispute_escrow_refund_notice: 'Financial Notice: Cancelling will mark the booking cancelled and schedule deposit refund to the player.',

    // Disputes
    disputes_title: 'Match Dispute Resolution Center',
    disputes_subtitle: 'Review disputed match reports, verify evidence, and finalize official scores',
    no_disputes_title: 'No Active Disputes',
    no_disputes_sub: 'All matches are progressing smoothly with verified scores',
    home_team: 'Home Team',
    away_team: 'Away Team',
    dispute_reason: 'Dispute Reason & Notes',
    resolve_btn: 'Resolve Dispute',
    resolve_modal_title: 'Resolve Match Dispute',
    final_decision_label: 'Final Decision:',
    home_win_opt: 'Home Team Victory',
    away_win_opt: 'Away Team Victory',
    draw_opt: 'Confirm Draw',
    cancelled_opt: 'Cancel & Refund',

    // Payout Settlements
    payout_title: 'Owner Financial Clearing & Settlements',
    payout_subtitle: 'Manage owner dues, monitor funds collected in your account, and confirm Cash/InstaPay payouts',
    tab_owner_matrix: 'Owner Ledger & Balances',
    tab_ledger: 'Transaction Stream',
    tab_requests: 'Incoming Withdrawal Requests',
    kpi_gross_volume: 'Total Venue Volume',
    kpi_gross_subtext: 'Gross registered booking value',
    kpi_online_collected: 'Collected in Platform Account',
    kpi_online_subtext: 'Online deposits in platform account',
    kpi_platform_commission: 'Net Platform Revenue',
    kpi_platform_subtext: 'Net platform commissions earned',
    kpi_pending_dues: 'Ready for Payout (Completed)',
    kpi_pending_subtext: 'Revenues from finished matches',
    kpi_escrow_held: 'Held Escrow (Upcoming)',
    kpi_escrow_subtext: 'Held securely until match completion',
    upcoming_escrow_note: 'Held for upcoming match',
    kpi_total_settled: 'Total Settled & Paid Out',
    kpi_settled_subtext: 'Transfers successfully paid to owners',
    owner_statement_col: 'Owner Name',
    gross_volume_col: 'Total Bookings',
    online_collected_col: 'Collected in Account',
    platform_fee_col: 'Platform Commission',
    settled_payouts_col: 'Previously Settled',
    net_withdrawable_col: 'Net Payable to Owner',
    ready_for_payout: 'Ready for Payout',
    no_dues: 'Fully Settled',
    negative_due: 'Due from Owner',
    no_destination_registered: 'Not Registered Yet',
    settle_now_btn: 'Settle Balance',
    payout_modal_title: 'Settle & Pay Owner Dues',
    amount_to_transfer: 'Amount to Transfer (EGP) *',
    transfer_method: 'Transfer Method *',
    vodafone_cash: 'Vodafone Cash',
    instapay: 'InstaPay',
    bank_transfer: 'Bank Transfer',
    cash_direct: 'Direct Cash Handover',
    wallet_number_account: 'Wallet Number / Account *',
    reference_number: 'Receipt Reference ID *',
    confirm_payout_btn: 'Confirm Settlement & Update Balance',
    settlement_success: 'Owner payout settled and balance updated successfully',

    // 1v1 League
    league_title: '1v1 Match League',
    league_subtitle: 'Manage player rankings, approve contenders, control registration gates, and update stats',
    gate_open_label: 'Registration Open',
    gate_closed_label: 'Registration Closed',
    add_player_manual: 'Add Player Manually',
    wipe_season_title: 'Start New Season',
    tab_standings: 'Rankings & Leaderboard',
    tab_registrations: 'Pending Registrations',
    rank_col: 'Rank',
    player_col: 'Player',
    total_points_col: 'Total Points',
    skill_points_col: 'Skill Points',
    goals_col: 'Goals',
    titles_col: 'Titles',
    trend_col: 'Trend / Level',
    trend_up: 'Upward',
    trend_stable: 'Stable',
    trend_down: 'Downward',
    add_player_modal_title: 'Add New 1v1 Contender',
    initial_points: 'Initial Points',
    edit_player_modal_title: 'Edit Player Statistics',

    // Tournament Control
    tournaments_title: 'Tournament Command Center',
    tournaments_subtitle: 'Manage open championships, generate brackets, and advance stages',
    no_tournaments_title: 'No Tournaments Found',
    tournament_name_col: 'Tournament Name',
    teams_count_col: 'Registered Teams',
    generate_bracket_btn: 'Generate Bracket',
    stage_col: 'Current Stage',

    // CRM Settings
    crm_title: 'Broadcast Center & System Settings',
    crm_subtitle: 'Send targeted push broadcasts to players and owners, and control app maintenance mode',
    broadcast_card_title: 'Send Instant Push Notification',
    target_audience_label: 'Target Audience:',
    audience_all: 'All Users (Players & Owners)',
    audience_players: 'Players Only',
    audience_owners: 'Stadium Owners Only',
    notif_title_label: 'Notification Title',
    notif_body_label: 'Notification Message Details',
    notif_title_placeholder: 'Example: Upcoming 1v1 Tournament Schedule Update',
    notif_body_placeholder: 'Write message details clearly...',
    send_notif_btn: 'Send Broadcast Now',
    maintenance_title: 'Application Maintenance Mode',
    maintenance_desc: 'Temporary lockdown during major updates. When enabled, bookings will pause and users will see the maintenance screen.',
    maintenance_active_status: 'Maintenance Mode Active',
    maintenance_inactive_status: 'Service Operating Normally',
    enable_maintenance: 'Enable Maintenance',
    disable_maintenance: 'Disable Maintenance',

    // Missing keys discovered in deep audit
    live_stream: 'Live',
    maintenance_toggle: 'Maintenance Toggle',
    pending_approval: 'Pending Approval',
    pending_note: 'Your request has been received and will be reviewed by the Co-Founder. You will be notified shortly.',
    infra_health_title: 'Infrastructure Health',
    infra_db: 'Database',
    infra_db_status: 'Connected',
    infra_region: 'Server Region',
    infra_rpc: 'Atomic RPC Functions',
    infra_rpc_status: 'Active',
    toast_owner_approved: 'Owner verified and stadium approved successfully',
    toast_owner_rejected: 'Audit request rejected',
    toast_owner_added: 'Owner and stadium added and activated successfully',
    toast_fill_required: 'Please fill in all required fields',
    toast_fail_generic: 'Operation failed, please try again later',
    toast_gate_opened: 'Registration gate opened successfully',
    toast_gate_closed: 'Registration gate closed',
    toast_season_wiped: 'Season reset and new cycle started successfully',
    toast_player_approved: 'Player approved and added to leaderboard',
    toast_player_rejected: 'Registration rejected',
    toast_player_added: 'Player added to 1v1 league successfully',
    toast_stats_saved: 'Player stats updated successfully',
    toast_bracket_generated: 'Tournament bracket generated successfully',
    toast_status_updated: 'Tournament status updated successfully',
    toast_maintenance_on: 'Maintenance mode activated successfully',
    toast_maintenance_off: 'Maintenance mode deactivated, platform is live',
    toast_broadcast_sent: 'Broadcast notification sent successfully',
    toast_broadcast_fill: 'Please provide a notification title and message body',
    try_different_filters: 'Try adjusting your search criteria or filters',
    preview_doc: 'Document Preview',
    open_in_new_tab: 'Open in New Window',

    // Login & Auth
    login_title: 'Sign In to Panel',
    login_sub: 'Enter your email and password to access the admin panel',
    email_label: 'Email Address',
    password_label: 'Password',
    full_name_label: 'Full Name',
    phone_label: 'Phone Number',
    btn_login: 'Sign In',
    btn_register: 'Request New Admin Account',
    already_have_account: 'Already have an account? Sign in',
    send_admin_request: 'Submit Admin Activation Request',

    // Banners & Ads Management
    banners_title: 'Banners & Interactive Ads Management',
    banners_subtitle: 'Manage in-app banner campaigns, image uploads, display durations, and engagement metrics',
    add_new_banner: 'Create New Banner',
    edit_banner: 'Edit Banner Details',
    total_banners: 'Total Banners',
    active_banners: 'Currently Active',
    total_banner_views: 'Total Views',
    total_banner_clicks: 'Total Clicks',
    ctr_rate: 'Engagement Rate (CTR)',
    banner_title: 'Banner / Campaign Title',
    banner_title_placeholder: 'e.g., Summer Stadium Discount Promotion...',
    banner_desc: 'Extra Description (Optional)',
    banner_desc_placeholder: 'Additional details about the promotion or ad...',
    banner_image: 'Banner Image',
    upload_image_note: 'Drag & drop image here or click to browse (PNG, JPG, WebP up to 5MB)',
    target_url: 'Target URL / Action (Optional)',
    target_url_placeholder: 'https://example.com/promo or internal screen route',
    placement: 'Display Placement',
    placement_all: 'All Placements',
    placement_home_slider: 'Home Screen Slider',
    placement_popup: 'Pop-up Modal',
    placement_tournaments: 'Tournaments Screen',
    duration_seconds: 'Slide Duration (Seconds)',
    duration_seconds_hint: 'How long the banner is shown before advancing to next slide (Default: 5s)',
    start_date: 'Start Date & Time',
    end_date: 'End Date & Time (Optional)',
    priority_order: 'Priority Order',
    priority_order_hint: 'Lower numbers display first (e.g., 1 before 2)',
    banner_status: 'Banner Status',
    status_active: 'Active & Running',
    status_disabled: 'Disabled',
    status_expired: 'Expired',
    status_scheduled: 'Scheduled',
    confirm_delete_banner: 'Are you sure you want to permanently delete this banner? This action cannot be undone.',
    banner_saved_success: 'Banner saved successfully',
    banner_deleted_success: 'Banner deleted successfully',
    banner_status_updated: 'Banner status updated successfully',
    no_banners_found: 'No banners created yet',
    no_banners_sub: 'Click "Create New Banner" to launch your first banner ad in the app',
    change_image: 'Change Image',
    select_image_required: 'Please select a banner image first',
    uploading_image: 'Uploading image to cloud storage...',
    banner_active_now: 'Active Now',
    banner_inactive: 'Disabled',
    filter_by_status: 'Status',
    filter_by_placement: 'Placement',
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('vsp_admin_lang') || 'ar';
  });

  useEffect(() => {
    localStorage.setItem('vsp_admin_lang', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }, [lang]);

  const toggleLanguage = () => {
    setLang((prev) => (prev === 'ar' ? 'en' : 'ar'));
  };

  const t = (key, params = {}) => {
    let str = translations[lang]?.[key] || key;
    if (params && typeof params === 'object' && Object.keys(params).length > 0) {
      Object.keys(params).forEach((p) => {
        str = str.replace(new RegExp(`\\{${p}\\}`, 'g'), params[p]);
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t, isRTL: lang === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
